   services:
     db:
       image: postgres:17
       environment: 
         POSTGRES_DB: apartmentDB
         POSTGRES_USER: user
         POSTGRES_PASSWORD: pass
       volumes:
         - db-data:/var/lib/postgresql/data
     backend:
       build: ./backend
       depends_on:
         - db
       environment:
         DATABASE_URL: postgres://user:pass@db:5432/apartmentDB
       ports:
         - "8080:8080"
     frontend:
       build: ./frontend
       depends_on:
         - backend
       ports:
         - "3000:3000"
   volumes:
     db-data: